services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: ml_engineer_backend

    ports:
      - "8000:8000"

    restart: unless-stopped

    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/models:/app/models
      - ./backend/reports:/app/reports
      - ./backend/mlruns:/app/mlruns

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: ml_engineer_frontend

    ports:
      - "8501:8501"

    environment:
      API_URL: http://backend:8000

    depends_on:
      - backend

    restart: unless-stopped